# Generated by Django 3.2.12 on 2022-03-11 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='place',
            new_name='movie',
        ),
    ]
